CREATE DATABASE BilgiYarismasiOyunu
GO
USE BilgiYarismasiOyunu
GO
CREATE TABLE Cevaplar(CevapID int IDENTITY PRIMARY KEY,
													 Cevap varchar(20))
CREATE TABLE SoruTipleri(TipID int IDENTITY PRIMARY KEY,
													 Tip varchar(20))

CREATE TABLE Sorular(SoruID int IDENTITY ,
													   Soru varchar(250),
													   A varchar(100),
													   B varchar(100),
													   C varchar(100),
													   D varchar(100),
													   Cevap int REFERENCES Cevaplar(CevapID),
													   SoruTipi int REFERENCES SoruTipleri(TipID))


SELECT * FROM Sorular
SELECT * FROM SoruTipleri
SELECT * FROM Cevaplar

INSERT INTO Cevaplar VALUES ('A'),('B'),('C'),('D')
INSERT INTO SoruTipleri VALUES ('Kolay'),('Zor')

INSERT INTO Sorular VALUES('“Sinekli Bakkal” Romanýnýn Yazarý Aþaðýdakilerden Hangisidir?',
															'Reþat Nuri Güntekin',
															'Halide Edip Adývar',
															'Ziya Gökalp',
															'Ömer Seyfettin',
															2,
															2),
															('Aþaðýda Verilen Ýlk Çað Uygarlýklarýndan Hangisi Yazýyý Ýcat Etmiþtir?',
															'Hititler',
															'Elamlar',
															'Sümerler',
															'Urartular',
															3,
															2),
															('Tsunami Felaketinde En Fazla Zarar Gören Güney Asya Ülkesi Aþaðýdakilerden Hangisidir?',
															'Endonezya',
															'Srilanka',
															'Tayland',
															'Hindistan',
															1,
															1),
															('2003 Yýlýnda Euro Vizyon Þarký Yarýþmasýnda Ülkemizi Temsil Eden ve Yarýþmada Birinci Gelen Sanatçýmýz Kimdir?',
															'Grup Athena',
															'Sertap Erener',
															'Þebnem Paker',
															'Ajda Pekkan',
															2,
															1),
															('Romen Rakamýnda Hangi Sayý Yoktur?',
															'0',
															'50',
															'100',
															'1000',
															1,
															1),															
															('Hangi Ülkenin Ýki Tane Baþkenti Vardýr?',
															'Venezuela',
															'Cibuti',
															'El Salvador',
															'Güney Afrika',
															4,
															2),													
															('Hangi Ýlimizde Demiryolu Yoktur?',
															'Batman',
															'Aydýn',
															'Muðla',
															'Kütahya ',
															3,
															2),													
															('Bir Sebepten Dolayý Tek Kulaðýna Küpe Takan Osmanlý Padiþahý Kimdir?',
															'Kanuni Sultan Süleyman',
															'Yavuz Sultan Selim',
															'Orhan Bey',
															'Fatih Sultan Selim',
															2,
															1),													
															('Üç Büyük Dince Kutsal Sayýlan Þehir Hangisidir?',
															'Mekke',
															'Kudüs',
															'Roma',
															'Ýstanbul',
															2,
															1),											
															('Aspirinin Hammaddesi Nedir?',
															'Söðüt',
															'Köknar',
															'Kavak',
															'Meþe',
															1,
															2)

SELECT Sorular.SoruID,Sorular.Soru,Sorular.A,Sorular.B,Sorular.C,Sorular.D,Sorular.Cevap,Cevaplar.Cevap,Sorular.SoruTipi,SoruTipleri.Tip
FROM     Cevaplar INNER JOIN
                  Sorular ON Cevaplar.CevapID = Sorular.Cevap INNER JOIN
                  SoruTipleri ON Sorular.SoruTipi = SoruTipleri.TipID
				  where SoruTipleri.Tip='Kolay'

INSERT INTO Sorular VALUES(' Türkiye’nin en eski þehri hangisidir?',
															'Ýstanbul',
															'Ankara',
															'Eskiþehir',
															'Hakkari',
															4,
															2),('Latin Harfleri ile çýkarýlan ilk gazete hangisidir?',
															'Mardin Gazetesi',
															'Ýstanbul Gazetesi',
															'Ankara Gazetesi',
															'Burdur Gazetesi',
															1,
															2),('"Büyük Britanyadaki baþkentleri gezdim" diyen biri hangi þehre gittiðini söylemiþ olmaz?',
															'Londra',
															'Dublin',
															'Cardiff',
															'Edinburg',
															2,
															1),('Hangisi "kesinlikle" anlamýna gelmez?',
															'Katiyen',
															'Kesinkes',
															'Pekâlâ',
															'Daima',
															4,
															1),('"Aðustosun yarýsý yaz" þeklinde baþlayan atasözünün devamý nasýldýr?',
															'Yarýsý güzdür',
															'Yarýsý bahardýr',
															'Yarýsý kýþtýr',
															'Yarýsý yazdýr',
															3,
															1),('2008de Newcastle Üniversitesinin 556.387 kiþi ve 927 soyaðacý üzerinde yaptýðý araþtýrmada hangisinin erkek çocuklarý olma ihtimalinin kýz çocuklarý olma ihtimalinden daha fazla olduðu sonucuna ulaþýlmýþtýr?',
															'Kýz kardeþi daha çok olan kadýnlarýn',
															'Kýz kardeþi daha çok olan erkeklerin',
															'Erkek kardeþi daha çok olan kadýnlarýn',
															'Erkek kardeþi daha çok olan erkeklerin',
															4,
															2),('Hangisi bir deyimde de adý geçen bir tür güvercindir?',
															'Baklacý kekliði',
															'Yulafçý turnasý',
															'Arpacý kumrusu',
															'Darýcý bülbülü',
															3,
															1),('Cebelitarýk Boðazý hangi ikisini birleþtirir?',
															'Akdeniz ve Atlas Okyanusu',
															'Atlas Okyanusu ve Büyük Okyanus',
															'Hazar Denizi ve Aral Gölü',
															'Sarý Deniz ve Hint Okyanusu',
															1,
															1),('Al Pease, Formula 1 tarihinde, hangi sebepten dolayý yarýþmadan diskalifiye edilen ilk ve tek sporcudur?',
															'Emniyet kemeri takmamak',
															'Çok yavaþ gitmek',
															'Ehliyetini evde unutmak',
															'Araçta müzik dinlemek',
															2,
															2),('"Dikkate þayan" ne demektir?',
															'Deðerli',
															'Önemsiz',
															'Basit',
															'Özensiz',
															1,
															1)

INSERT INTO Sorular VALUES('Hangisi bir çeþit acý bala verilen addýr?',
															'Deli bal',
															'Mecnun bal',
															'Aþýk bal',
															'Divane bal',
															1,
															1),('Hangisi atomlarda bulunan temel parçacýklardan biri deðildir?',
															'Proton',
															'Nötron',
															'Elektron',
															'Megatron',
															4,
															1),('Hangi edebiyatçý TBMM''de milletvekilliði yapmamýþtýr?',
															'Yahya Kemal Beyatlý',
															'Sait Faik Abasýyanýk',
															'Halide Edip Adývar',
															'Mehmet Akif Ersoy',
															2,
															2),('1959''da New York''taki bir þampiyonaya erkek kýlýðýnda katýlan Rena Kanogoki, hangi alanda altýn madalya kazanmýþ ve kadýn olduðu anlaþýlýnca madalyasýný iade etmek zorunda kalmýþtýr?',
															'Satranç',
															'Judo',
															'Eskrim',
															'Okçuluk',
															2,
															2),('Cumhuriyet ilan edildikten sonra hangi ülkenin temsilcisi Türkiye''ye diðerlerinden daha önce diplomatik ziyarette bulunmuþ ve Mustafa Kemal tarafýndan kabul edilmiþtir?',
															'Afganistan',
															'Fransa',
															'ABD',
															'Birleþik Krallýk',
															2,
															2),('Fransa''dan trene binip deniz altýndaki Manþ Tüneli''nden geçen biri hangi ülkeye ulaþýr?',
															'Birleþik Krallýk',
															'Almanya',
															'Ýzlanda',
															'Portekiz',
															1,
															1),('Çekimleri 46 hafta süren ve "En uzun kesintisiz film çekimi" unvanýyla Guinness Dünya Rekorlarýna giren film hangisidir?',
															'Kýþ Uykusu',
															'Ucuz Roman',
															'Gözleri Tamamen Kapalý',
															'Aðýr Roman',
															3,
															2),('"Roland-Garros þampiyonu" olan biri hangi sporu yapýyordur?',
															'Tenis',
															'Golf',
															'Bilardo',
															'Boks',
															1,
															1),('Afrika kýtasýnýn Kilimanjaro''dan sonraki en yüksek daðý olan Kenya Daðý hangi ülkededir?',
															'Kenya',
															'Güney Afrika',
															'Nijerya',
															'Fas',
															1,
															1),('Hangisi "havuç"a verilen bir addýr?',
															'Havayavaran',
															'Topraðagiren',
															'Yeregeçen',
															'Karakaçan',
															3,
															1)

INSERT INTO Sorular VALUES('Hangisi TDK sözlüklerinde tanýmý olan bir ifade deðildir?',
															'Yýldýzlarý barýþmamak',
															'Perileri baðdaþmak',
															'Kafasý uyuþmak',
															'Gönlü çelinmek',
															3,
															2),('"Linyit", "antrasit" gibi türleri olan ve büyük ölçüde karbondan oluþan hangisidir?',
															'Alüminyum',
															'Bor',
															'Obsidiyen',
															'Kömür',
															4,
															1),('1986''da, 87 yolcu ve 7 mürettebatýyla SSCB''nin Samara kentine inmekte olan bir yolcu uçaðýnýn kaptan pilotu yardýmcýsýyla kokpit camlarý kapalý þekilde uçaðý piste indirebileceði üzerine iddiaya girmiþ ve ne olmuþtur?',
															'Uçak, Hazar Denizi''ne inmiþtir',
															'Uçak sorunsuzca piste inmiþtir',
															'Uçak kaza yapmýþ 70 kiþi ölmüþtür',
															'Uçak, Erzurum''a inmiþtir',
															3,
															2),('Morgan Freeman, kariyerindeki tek Oscar''ý hangi filmdeki rolüyle kazanmýþtýr?',
															'Milyonluk Bebek',
															'Esaretin Bedeli',
															'Yedi',
															'Affedilmeyen',
															1,
															2),('Tamamen otomatik sistemlerle donatýlmýþ ve üretim gerçekleþtirirken insan gücüne ihtiyaç duyulmamasýný hedefleyen üretim yöntemine ne ad verilir?',
															'Sýcak fabrikalar',
															'Soðuk fabrikalar',
															'Sessiz fabrikalar',
															'Karanlýk fabrikalar',
															4,
															2),('Ünlü çizgi karakterlerden hangisi fare deðildir?',
															'Sonic',
															'Mickey Mouse',
															'Jerry',
															'Speed Gonzales',
															1,
															1),('"Ressam sehpasý" anlamýna gelen kelimenin doðru yazýlýþý hangisidir?',
															'Þovalye',
															'Þövalye',
															'Þovale',
															'Þövale',
															4,
															1),('Þehre, surlardaki Lefke Kapýsý''ndan girip Yeþil Cami''yi ve Ayasofya Camii''ni ziyaret ettikten sonra göl kýyýsýnda çay içiyorsanýz neredesinizdir?',
															'Ayvalýk',
															'Ýznik',
															'Ezine',
															'Bergama',
															2,
															1),('Ayný adlý romandan sinemaya uyarlanan, akýl hastasý numarasý yapan bir mahkumu anlatan ve baþrolünde Jack Nicholson''ýn oynadýðý film hangisidir?',
															'Esaretin Bedeli',
															'Olaðan Þüpheliler',
															'Guguk Kuþu',
															'Yeþil Yol',
															3,
															1),('Hangisinin 100. yýlý bir artýk yýla denk gelmektedir?',
															'30 Aðustos Zaferi',
															'TBMM''nin Ankara''da ilk açýlýþý',
															'Türkiye''de cumhuriyetin ilaný',
															'Atatürk''ün Samsun''a çýkýþý',
															3,
															1)

INSERT INTO Sorular VALUES('Hangisi TDK sözlüklerinde tanýmý olan bir ifade deðildir?',
															'Yýldýzlarý barýþmamak',
															'Perileri baðdaþmak',
															'Kafasý uyuþmak',
															'Gönlü çelinmek',
															3,
															2),('"Linyit", "antrasit" gibi türleri olan ve büyük ölçüde karbondan oluþan hangisidir?',
															'Alüminyum',
															'Bor',
															'Obsidiyen',
															'Kömür',
															4,
															1),('1986''da, 87 yolcu ve 7 mürettebatýyla SSCB''nin Samara kentine inmekte olan bir yolcu uçaðýnýn kaptan pilotu yardýmcýsýyla kokpit camlarý kapalý þekilde uçaðý piste indirebileceði üzerine iddiaya girmiþ ve ne olmuþtur?',
															'Uçak, Hazar Denizi''ne inmiþtir',
															'Uçak sorunsuzca piste inmiþtir',
															'Uçak kaza yapmýþ 70 kiþi ölmüþtür',
															'Uçak, Erzurum''a inmiþtir',
															3,
															2),('Morgan Freeman, kariyerindeki tek Oscar''ý hangi filmdeki rolüyle kazanmýþtýr?',
															'Milyonluk Bebek',
															'Esaretin Bedeli',
															'Yedi',
															'Affedilmeyen',
															1,
															2),('Tamamen otomatik sistemlerle donatýlmýþ ve üretim gerçekleþtirirken insan gücüne ihtiyaç duyulmamasýný hedefleyen üretim yöntemine ne ad verilir?',
															'Sýcak fabrikalar',
															'Soðuk fabrikalar',
															'Sessiz fabrikalar',
															'Karanlýk fabrikalar',
															4,
															2),('Ünlü çizgi karakterlerden hangisi fare deðildir?',
															'Sonic',
															'Mickey Mouse',
															'Jerry',
															'Speed Gonzales',
															1,
															1),('"Ressam sehpasý" anlamýna gelen kelimenin doðru yazýlýþý hangisidir?',
															'Þovalye',
															'Þövalye',
															'Þovale',
															'Þövale',
															4,
															1),('Þehre, surlardaki Lefke Kapýsý''ndan girip Yeþil Cami''yi ve Ayasofya Camii''ni ziyaret ettikten sonra göl kýyýsýnda çay içiyorsanýz neredesinizdir?',
															'Ayvalýk',
															'Ýznik',
															'Ezine',
															'Bergama',
															2,
															1),('Ayný adlý romandan sinemaya uyarlanan, akýl hastasý numarasý yapan bir mahkumu anlatan ve baþrolünde Jack Nicholson''ýn oynadýðý film hangisidir?',
															'Esaretin Bedeli',
															'Olaðan Þüpheliler',
															'Guguk Kuþu',
															'Yeþil Yol',
															3,
															1),('Hangisinin 100. yýlý bir artýk yýla denk gelmektedir?',
															'30 Aðustos Zaferi',
															'TBMM''nin Ankara''da ilk açýlýþý',
															'Türkiye''de cumhuriyetin ilaný',
															'Atatürk''ün Samsun''a çýkýþý',
															3,
															1)

INSERT INTO Sorular VALUES('Hangisi "eþek" ile eþ anlamlý deðildir?',
															'Enik',
															'Merkep',
															'Karakaçan',
															'Uzun kulaklý',
															1,
															1),('Hangi ülkede bir evin kapýsýný týklatýp kaçmak suçtur?',
															'Birleþik Krallýk',
															'Çin',
															'Küba',
															'Danimarka',
															1,
															2),('Aralýk 2021''de, Ýstanbul''da, Yemenli Muhammed Mukbel, üst üste kaç yumurta dizip yumurtalarýn düþmeden durmasýný saðlayarak Guinness Dünya Rekorlarýna gitmiþtir?',
															'4',
															'7',
															'10',
															'15',
															1,
															2),('Arjantin, Hollanda ve Almanya milli futbol takýmlarý için Türk basýnýnda kullanýlan lakaplar sýrasýyla hangileridir?',
															'Sambacýlar, Boðalar, Horozlar',
															'Portakallar, Sambacýlar, Tangocular',
															'Panzerler, Horozlar, Boðalar',
															'Tangocular, Portakallar, Panzerler',
															4,
															1),('Guinness Dünya Rekorlarýna göre Sri Lanka''da bulunan ve insan eliyle dikilmiþ bilinen en eski aðaç olan "Sri Maha Bodhiya" adlý aðaç hangi tarihte dikilmiþtir?',
															'MÖ 1288',
															'MÖ 288',
															'MS 288',
															'MS 1288',
															2,
															2),('Hangisi 1991''de Ýngiltere milli futbol takýmýnda beþ defa forma giymiþ bir futbolcunun soyadýdýr?',
															'Salako',
															'Davaro',
															'Feyzo',
															'Maho',
															1,
															2),('Basketbolda çembere yan durarak tek elle baþ üzerinden geçirilerek atýlan þuta ne ad verilir?',
															'Cemþat',
															'Plonjon',
															'Hukþat',
															'Degaj',
															3,
															2),('Okuduðunuz tarih kitabýnda anlatýlan savaþta adý geçenlerden biri Romen Diyojen''se diðeri muhtemelen hangisidir?',
															'Gazneli Mahmut',
															'Cengiz Han',
															'Timur',
															'Alparslan',
															4,
															2),('Asýl adý Marie-Henri Beyle olan, 17 yaþýnda Napolyon Bonapart''ýn ordusuna katýlan ve Napolyon''un Rusya seferine de giden, "Kýzýl ile Kara" adlý romaný yazan yazar kimdir?',
															'Stendhal',
															'Voltaire',
															'Balzac',
															'Gogol',
															1,
															2),('2017''de ABD''de yayýmlanan bir araþtýrmaya göre, köpekleri beraber olduklarý kiþiden hoþlanmayan kiþilerin yüzde 54''ü hangisini yapmaya meyillidir?',
															'Köpeðini terk etmeye',
															'Ýliþkisini bitirmeye',
															'Eve kedi almaya',
															'Evi terk etmeye',
															2,
															2)